const sample = {
  serialNumber: "1",
  type: "Whole Blood",
  issuedAt: "2024-01-10T19:59:21.873",
  isRevised: false,
  test: {
    id: "ABCDE1234567890HEM",
    orderNumber: "ABCDE1234567890",
    type: "HEM",
    results: [
      {
        number: -1,
        result: 2.2,
        parameter: "WBC",
        unit: "10*3/uL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 3.3,
        parameter: "RBC",
        unit: "10*6/uL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 4.4,
        parameter: "HGB",
        unit: "g/dL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 5.5,
        parameter: "HCT",
        unit: "%",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 6.6,
        parameter: "MCV",
        unit: "fL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 7.7,
        parameter: "MCH",
        unit: "pg",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 8.8,
        parameter: "MCHC",
        unit: "g/dL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 9.9,
        parameter: "plateletCount",
        unit: "10*3/uL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 10.1,
        parameter: "RDWCV",
        unit: "%",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 11.11,
        parameter: "MPV",
        unit: "fL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 12.12,
        parameter: "Neutrophils",
        unit: "10*3/uL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 13.13,
        parameter: "Lymphocytes",
        unit: "10*3/uL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 14.14,
        parameter: "Monocytes",
        unit: "10*3/uL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 15.15,
        parameter: "Eosinophils",
        unit: "10*3/uL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 16.16,
        parameter: "Basophils",
        unit: "10*3/uL",
        abnormalFlag: "N",
      },
      {
        number: -1,
        result: 17.17,
        parameter: "IG",
        unit: "10*3/uL",
        abnormalFlag: "N",
      },
    ],
    issuedAt: "2024-01-10T19:58:35.47",
    samples: ["1"],
    patient: "P?talal.lahham",
  },
  patient: {
    role: "P",
    name: "Talal Lahham",
    phone: "0784561238",
    email: "talal.lahham@ctc.ju.com",
    gender: "M",
    dob: "2000-09-06",
    isActive: true,
    startDate: "2023-11-15T09:10:11.703",
    endDate: null,
    username: "P?talal.lahham",
  },
  requester: {
    role: "R",
    name: "Dr. Abdullah Abadi",
    phone: "0789988774",
    email: "abdullah.abadi@ctc.ju.com",
    gender: "M",
    dob: "1111-11-11",
    isActive: true,
    startDate: "2023-11-15T13:05:19.622",
    endDate: null,
    username: "R?abdullah.abadi",
  },
  tester: {
    role: "T",
    name: "Feddah Lababneh",
    phone: "0789966332",
    email: "feddah.lababneh@ctc.ju.com",
    gender: "F",
    dob: "1111-11-11",
    isActive: true,
    startDate: "2023-11-15T13:01:23.362",
    endDate: null,
    username: "T?feddah.lababneh",
    password: "feddah.lababneh",
  },
};
